version: 2
jobs:
  build:
    # Variable expansion in working_directory not supported at this time
    # You will need to modify the code below to reflect your github account/repo setup
    working_directory: /go/src/github.com/AlyaZka/invoicer-chapter3
    docker:
      - image: circleci/golang:1.11
    environment:
      GO15VENDOREXPERIMENT: 1
    branches:
      only:
        - master
    steps:
      - run:
          name: ZAP baseline test of application
          # Only fail on error code 1, which indicates at least one FAIL was found.
          # error codes 2 & 3 indicate WARN or other, and should not break the run
          command: |
            echo "ZAP baseline test of application"
            (
            docker pull owasp/zap2docker-weekly && \
            docker run -t owasp/zap2docker-weekly zap-baseline.py \
                -u https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/master/zap-baseline.conf \
                -t http://tolg-invoicer-202311131816-invoicer-api.eba-8ctdfapa.eu-north-1.elasticbeanstalk.com/ || \
            if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
            )
            
